import { Reshaped, View, Text, Button, Tabs, Divider } from "reshaped";

import "./globals.css";
import "reshaped/themes/reshaped/theme.css";
import { ClerkProvider } from "@clerk/nextjs/app-beta";
import Docs from "@/components/Icons/DocsIcon";
import Template from "@/components/Icons/TemplateIcon";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body>
          <Reshaped theme="reshaped">
            {/* Header */}
            <View>
              {/* Upper part */}
              <View
                paddingBlock={4}
                paddingInline={6}
                className="flex flex-row justify-between"
              >
                <Text
                  variant="featured-2"
                  weight="bold"
                  className="bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-violet-500"
                >
                  Business platform
                </Text>

                <Button>Search</Button>
              </View>
              <Divider />

              {/* Lower part */}
              <View paddingBlock={0} paddingInline={6}>
                <Tabs variant="borderless">
                  <Tabs.List>
                    <Tabs.Item value="0" icon={<Docs />}>
                      Documents
                    </Tabs.Item>
                    <Tabs.Item value="1" icon={<Template />}>
                      Templates
                    </Tabs.Item>
                  </Tabs.List>
                </Tabs>
              </View>
              <Divider blank />
            </View>
            {children}
          </Reshaped>
        </body>
      </ClerkProvider>
    </html>
  );
}
