import { ClerkProvider } from '@clerk/nextjs';
import { Reshaped } from 'reshaped';
import 'reshaped/themes/reshaped/theme.css';
import FqlxClientProvider from './FqlxClientProvider';
import '@/app/globals.css';

export const metadata = {
  title: 'Business Planner',
  description: 'Generated by Next.js',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <ClerkProvider>
        <body>
          <Reshaped theme='reshaped'>
            <FqlxClientProvider>{children}</FqlxClientProvider>
          </Reshaped>
        </body>
      </ClerkProvider>
    </html>
  );
}
